### ISSUE TITLE
[Fearure Request] set QueryString value for Token Name

### ISSUE THREAD

**Issue by tequdev** [nixer89/xrpl-services-xapp-token-trasher#1]
If I open an xApp with the following QueryString set, is it possible to set the value for Token Name input?
---

`https://xumm.app/detect/xapp:nixer.tokentrasher?tokenName=CSC`

then filter will be filled.

![image](https://user-images.githubusercontent.com/69445828/155829921-0c778326-a3dd-41d2-86ba-7b8843f4ebeb.png)

**Comment by nixer89** [comment]
Hi, 

You can do that already by adding "issuer" and "currency" as query parameters like this:

https://xumm.app/detect/xapp:nixer.tokentrasher?issuer=rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr&currency=CSC

Is this something you can work with or you really just want to filter by name?

**Comment by tequdev** [comment]
Thank you.
The `issuer` and `currency` parameters are the best way to specify.

I will make it possible to go to TokenTrasher from my site (https://trustline-checker.tequ.dev/) in the future.

Thanks again for your help.
